vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=auto-safe
profile=high-quality
keep-open=yes  # keep MPV open after playback
save-position-on-quit=yes
audio-file-auto=fuzzy  # auto-detect audio files
sub-auto=fuzzy  # auto-detect subtitles
gpu-shader-cache-dir="~~/shaders_cache"
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r3.hook"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"

# settings for uosc intergrate
osd-bar=no
# border=no
